### ISSUE TITLE
Error when creating ID

### ISSUE THREAD

**Issue by wirehack7** [mnaamani/node-otr-talk#1]
I hope this project is not dead, I really like the idea of it.

I am getting errors when running `otrtalk profiles add`:
```
notadmin@helios:~$ otrtalk profiles add
Enter a profile name (alphanumeric characters only)
  profile name: (node:16292) V8: /usr/lib/node_modules/otrtalk/node_modules/enet/build/enet.js:11 Invalid asm.js: Invalid member of stdlib
paX
/usr/lib/node_modules/otrtalk/node_modules/enet/build/enet.js:9
var Module;this["Module"]=Module={"preRun":(function(){Module["jsapi"]={};Module["jsapi"]["init"]=cwrap("jsapi_init","",["number"]);Module["jsapi"]["enet_host_create_client"]=cwrap("jsapi_enet_host_create_client","number",["number","number","number","number"]);Module["jsapi"]["enet_host_create_server"]=cwrap("jsapi_enet_host_create_server","number",["number","number","number","number","number","number"]);Module["jsapi"]["enet_host_from_socket"]=cwrap("jsapi_enet_host_from_socket","number",["number","number","number","number","number","number","number"]);Module["jsapi"]["enet_host_bind"]=cwrap("jsapi_enet_host_bind","",["number"]);Module["jsapi"]["host_get_socket"]=cwrap("jsapi_host_get_socket","number",["number"]);Module["jsapi"]["host_get_receivedAddress"]=cwrap("jsapi_host_get_receivedAddress","number",["number"]);Module["jsapi"]["enet_host_connect"]=cwrap("jsapi_enet_host_connect","number",["number","number","number","number","number"]);Modu

Error: ENOENT: no such file or directory, scandir '/home/notadmin/.otrtalk'
    at Object.readdirSync (fs.js:806:3)
    at Object.FileStore.self.profiles (/usr/lib/node_modules/otrtalk/lib/profiles/otrtalk_profile_store.js:52:6)
    at Object.ProfilesManager.self.profiles (/usr/lib/node_modules/otrtalk/lib/profiles/profile_manager.js:15:16)
    at Object.ProfilesManager.self.count (/usr/lib/node_modules/otrtalk/lib/profiles/profile_manager.js:20:15)
    at Object.ProfilesManager.self.profileExists (/usr/lib/node_modules/otrtalk/lib/profiles/profile_manager.js:44:12)
    at /usr/lib/node_modules/otrtalk/lib/commands/cmd-profiles.js:54:11
    at ReadStream.<anonymous> (/usr/lib/node_modules/otrtalk/lib/commands/commander.js:837:5)
    at Object.onceWrapper (events.js:285:13)
    at ReadStream.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
```

How these could be resolved?

**Comment by wirehack7** [comment]
Ok, fixed with manually creating `~/.otrtalk` directory. But dependencies are really outdated. Will check if it's not too much work to just update them.
